Fix test_global_setup unit test
Current code in test_global_setup sets a non valid user_id and leaves it
like that for the rest of the tests, which can lead to error:

ValueError: A string is required in field user_id, not a _SentinelObject

An easy way to reproduce this error is to create a file called fail.txt
with the following content:

cinderlib.tests.unit.test_cinderlib.TestCinderlib.test_global_setup
cinderlib.tests.unit.test_serialization.TestSerialization.test_conn_to_and_from

And then run from the tox virtual environment:

    stestr run --serial --load-list=fail.txt

This patch fixes this issue by restoring the values after the test is
run.

Change-Id: I121bc20c1ac4d7c07a1bcd13df19fdb868e65857